# Generated by Django 5.2.6 on 2025-09-23 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Cidade"),
                ),
            ],
            options={
                "verbose_name": "Cidade",
                "verbose_name_plural": "Cidades",
            },
        ),
        migrations.CreateModel(
            name="Orcrim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Orcrim"),
                ),
                (
                    "sigla",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Sigla"
                    ),
                ),
                (
                    "area_abrangencia",
                    models.CharField(
                        choices=[
                            ("ocl", "OCL"),
                            ("ocr", "OCR"),
                            ("ocn", "OCN"),
                            ("oci", "OCI"),
                            ("nao_possui", "Não possui"),
                        ],
                        max_length=30,
                        verbose_name="Área de Abrangência",
                    ),
                ),
                ("area_atuacao", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Orcrim",
                "verbose_name_plural": "Orcrims",
            },
        ),
        migrations.CreateModel(
            name="CasaPrisional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome da Casa Prisional"
                    ),
                ),
                ("sigla", models.CharField(max_length=20, verbose_name="Sigla")),
                (
                    "delegacia_penitenciaria",
                    models.CharField(
                        choices=[
                            ("1dpr", "1ª DPR"),
                            ("2dpr", "2ª DPR"),
                            ("3dpr", "3ª DPR"),
                            ("4dpr", "4ª DPR"),
                            ("5dpr", "5ª DPR"),
                            ("6dpr", "6ª DPR"),
                            ("7dpr", "7ª DPR"),
                            ("8dpr", "8ª DPR"),
                            ("9dpr", "9ª DPR"),
                            ("10dpr", "10ª DPR"),
                            ("unid_esp", "Unidades Especiais"),
                        ],
                        max_length=20,
                        verbose_name="Delegacia Penitenciária",
                    ),
                ),
                (
                    "tipo_estrutura",
                    models.CharField(
                        choices=[
                            ("completa", "Completa (Pavilhão, Galeria, Cela)"),
                            ("intermediaria", "Intermediária (Galeria, Cela)"),
                            ("modular", "Módulo"),
                            ("apenas_alojamento", "Apenas Alojamento"),
                        ],
                        default="completa",
                        max_length=100,
                        verbose_name="Tipo de Estrutura",
                    ),
                ),
                (
                    "cidade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="controle.cidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Casa Prisional",
                "verbose_name_plural": "Casas Prisionais",
            },
        ),
        migrations.CreateModel(
            name="Galeria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Galeria"
                    ),
                ),
                (
                    "casa_prisional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controle.casaprisional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galeria",
                "verbose_name_plural": "Galerias",
            },
        ),
        migrations.CreateModel(
            name="Cela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Cela"
                    ),
                ),
                (
                    "casa_prisional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controle.casaprisional",
                    ),
                ),
                (
                    "galeria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controle.galeria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cela",
                "verbose_name_plural": "Celas",
            },
        ),
        migrations.CreateModel(
            name="Alojamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Alojamento"
                    ),
                ),
                (
                    "casa_prisional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controle.casaprisional",
                    ),
                ),
                (
                    "cela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controle.cela",
                    ),
                ),
                (
                    "galeria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controle.galeria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alojamento",
                "verbose_name_plural": "Alojamentos",
            },
        ),
        migrations.CreateModel(
            name="Pavilhao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Pavilhão"
                    ),
                ),
                (
                    "casa_prisional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controle.casaprisional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pavilhão",
                "verbose_name_plural": "Pavilhões",
            },
        ),
        migrations.CreateModel(
            name="Individuo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                (
                    "rg_cpf",
                    models.CharField(max_length=11, unique=True, verbose_name="RG/CPF"),
                ),
                ("data_nasc", models.DateField()),
                (
                    "alcunha",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Alcunha"
                    ),
                ),
                (
                    "codigo_detento",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Cód."
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos/", verbose_name="Foto"
                    ),
                ),
                (
                    "situacao_penal",
                    models.CharField(
                        choices=[
                            ("recolhido", "Recolhido"),
                            ("recolhido_tornozeleira", "Recolhido - Tornozeleira"),
                            ("liberdade", "Liberdade"),
                            ("foragido", "Foragido"),
                            ("removido", "Removido"),
                            ("procurado", "Procurado"),
                        ],
                        max_length=50,
                        verbose_name="Situação Penal",
                    ),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("fechado", "Fechado"),
                            ("semiaberto", "Semiaberto"),
                            ("aberto", "Aberto"),
                            ("provisorio", "Provisório"),
                            ("monitorado", "Monitorado"),
                            ("sem regime", "Sem Regime"),
                        ],
                        max_length=50,
                        verbose_name="Regime",
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "grau_importancia",
                    models.BooleanField(
                        default=False, verbose_name="Grau de importância"
                    ),
                ),
                (
                    "nivel_orcrim",
                    models.CharField(
                        choices=[
                            ("lider", "Líder"),
                            ("influente", "Influente"),
                            ("sem_expressao", "Sem Expressão"),
                        ],
                        default="sem_expressao",
                        max_length=20,
                        verbose_name="Nível de Hierarquia na Orcrim",
                    ),
                ),
                (
                    "alojamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="controle.alojamento",
                    ),
                ),
                (
                    "casa_prisional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="controle.casaprisional",
                    ),
                ),
                (
                    "cela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="controle.cela",
                    ),
                ),
                (
                    "galeria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="controle.galeria",
                    ),
                ),
                (
                    "orcrim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="controle.orcrim",
                        verbose_name="Orcrim",
                    ),
                ),
                (
                    "pavilhao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="controle.pavilhao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indivíduo",
                "verbose_name_plural": "Indivíduos",
            },
        ),
        migrations.AddField(
            model_name="galeria",
            name="pavilhao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="controle.pavilhao",
            ),
        ),
        migrations.AddField(
            model_name="cela",
            name="pavilhao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="controle.pavilhao",
            ),
        ),
        migrations.AddField(
            model_name="alojamento",
            name="pavilhao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="controle.pavilhao",
            ),
        ),
    ]
