# Generated by Django 5.2.6 on 2025-10-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcrim",
            name="logo_orcrim",
            field=models.ImageField(
                blank=True, null=True, upload_to="fotos/", verbose_name="Logo da Orcrim"
            ),
        ),
    ]
