# Generated by Django 5.2.6 on 2025-09-30 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individuo",
            name="grau_importancia",
        ),
    ]
