# Generated by Django 5.2.6 on 2025-09-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casaprisional",
            name="tipo_estrutura",
            field=models.CharField(
                choices=[
                    ("completa", "Completa (Pavilhão, Galeria, Cela)"),
                    ("intermediaria", "Intermediária (Galeria, Cela)"),
                    ("pavilhao", "Pavilhão"),
                    ("modular", "Módulo"),
                    ("apenas_alojamento", "Apenas Alojamento"),
                ],
                default="completa",
                max_length=100,
                verbose_name="Tipo de Estrutura",
            ),
        ),
    ]
