# Generated by Django 5.2.6 on 2025-10-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0002_alter_casaprisional_tipo_estrutura"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individuo",
            name="grau_importancia",
        ),
    ]
