# Generated by Django 5.2.6 on 2025-10-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0003_remove_individuo_grau_importancia"),
    ]

    operations = [
        migrations.AddField(
            model_name="galeria",
            name="orcrim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="controle.orcrim",
                verbose_name="Orcrim Relacionada",
            ),
        ),
    ]
