# Generated by Django 5.2.6 on 2025-10-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0003_alojamento_orcrim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individuo",
            name="rg_cpf",
            field=models.CharField(max_length=14, unique=True, verbose_name="RG/CPF"),
        ),
    ]
