# Generated by Django 5.2.6 on 2025-10-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0004_galeria_orcrim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orcrim",
            name="area_atuacao",
        ),
    ]
