# Generated by Django 5.2.6 on 2026-03-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0004_alter_individuo_rg_cpf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orcrim",
            options={
                "ordering": ["nome"],
                "verbose_name": "Orcrim",
                "verbose_name_plural": "Orcrims",
            },
        ),
    ]
