# Generated by Django 5.2.6 on 2026-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0005_alter_orcrim_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="galeria",
            name="orcrim",
        ),
        migrations.AddField(
            model_name="galeria",
            name="orcrims",
            field=models.ManyToManyField(
                blank=True,
                related_name="galerias",
                to="controle.orcrim",
                verbose_name="Orcrims Relacionadas",
            ),
        ),
    ]
