# Generated by Django 5.2.6 on 2026-03-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0006_remove_galeria_orcrim_galeria_orcrims"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individuo",
            name="regime",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fechado", "Fechado"),
                    ("semiaberto", "Semiaberto"),
                    ("aberto", "Aberto"),
                    ("provisorio", "Provisório"),
                    ("monitorado", "Monitorado"),
                    ("sem regime", "Sem Regime"),
                ],
                max_length=50,
                null=True,
                verbose_name="Regime",
            ),
        ),
    ]
