# Generated by Django 5.2.6 on 2026-03-29 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0007_alter_individuo_regime"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrada", models.DateTimeField(verbose_name="Data de Entrada")),
                (
                    "data_saida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Saída"
                    ),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "alojamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="controle.alojamento",
                    ),
                ),
                (
                    "casa_prisional",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="controle.casaprisional",
                    ),
                ),
                (
                    "cela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="controle.cela",
                    ),
                ),
                (
                    "galeria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="controle.galeria",
                    ),
                ),
                (
                    "individuo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_movimentacoes",
                        to="controle.individuo",
                    ),
                ),
                (
                    "pavilhao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="controle.pavilhao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
                "ordering": ["-data_entrada"],
            },
        ),
    ]
