# Generated by Django 5.2.6 on 2026-03-29 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0008_movimentacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacao",
            name="data_registro",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data do Registro no Sistema",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="data_entrada",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data de Entrada"
            ),
        ),
    ]
