# Generated by Django 5.2.6 on 2026-03-29 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0009_movimentacao_data_registro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="individuo",
            name="data_entrada_unidade",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Data de Entrada na Unidade (Real)",
            ),
        ),
    ]
