# Generated by Django 5.2.6 on 2026-03-30 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0010_individuo_data_entrada_unidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individuo",
            name="data_entrada_unidade",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Data de Entrada na Unidade (Real)",
            ),
        ),
    ]
