# Generated by Django 5.2.6 on 2026-03-30 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0011_alter_individuo_data_entrada_unidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacao",
            name="data_entrada",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data de Entrada"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="data_registro",
            field=models.DateField(
                auto_now_add=True, verbose_name="Data do Registro no Sistema"
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="data_saida",
            field=models.DateField(blank=True, null=True, verbose_name="Data de Saída"),
        ),
    ]
