# Generated by Django 5.2.6 on 2026-03-31 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0012_alter_movimentacao_data_entrada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacao",
            name="data_entrada",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Data de Entrada",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="data_registro",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Data do Registro no Sistema"
            ),
        ),
    ]
